### ISSUE TITLE
Problem to decode response Map from method getAllByClientIdAndDateBetween

### ISSUE THREAD

**Issue by Mishelder** [Mishelder/todo-tasker#2]
"GET /range?date_from={date_from}&date_to={date_to}&client_id={client_id}"
fun getAllByClientIdAndDateBetween(
    @Param("date_from") dateFrom: String,
    @Param("date_to") dateTo: String,
    @Param("client_id") clientId: Int
  ): **Map<LocalDate, List<TaskDtoResponse>>**

java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 3 path $.
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:384) ~[gson-2.8.8.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215) ~[gson-2.8.8.jar:na]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.8.jar:na]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:186) ~[gson-2.8.8.jar:na]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[gson-2.8.8.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:897) ~[gson-2.8.8.jar:na]
	at feign.gson.GsonDecoder.decode(GsonDecoder.java:50) ~[feign-gson-11.7.jar:na]

**Comment by Mishelder** [comment]
Possible solution is to create dto object for response map

**Comment by Mishelder** [comment]
resolve problem with adding object mapper with module **JavaTimeModule**
